version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
  - package_manager: "docker"
    directory: "/"
      schedule:
        interval: "daily"
