steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Clean up old Versions
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSIONS=$(gcloud app versions list --service tobi-ui --sort-by '~version' --format 'value(version.id)')
        COUNT=0
        echo "Keeping the 10 latest versions of the tobi-ui service"
        for VERSION in $VERSIONS
        do
          ((COUNT++))
          if [ $COUNT -gt 10 ]
          then
            echo "Going to delete version $VERSION of the tobi-ui service."
            gcloud app versions delete $VERSION --service tobi-ui -q
          else
            echo "Going to keep version $VERSION of the tobi-ui service."
          fi
        done
