steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Generate manifest
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed "s#_PROJECT_ID#${_PROJECT_ID}#g" appengine_templates/app.yaml.tpl | \
        sed "s#_VM_INTERNAL_URL#${_VM_INTERNAL_URL}#g" | \
        sed "s#_VM_EXTERNAL_WEB_URL#${_VM_EXTERNAL_WEB_URL}#g" | \
        sed "s#_VM_EXTERNAL_CLIENT_URL#${_VM_EXTERNAL_CLIENT_URL}#g" | \
        sed "s#_BLAISE_API_URL#${_BLAISE_API_URL}#g" > app.yaml

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Print Output
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        cat app.yaml

  - name: "gcr.io/cloud-builders/gcloud"
    id: Deploy service for testing
    args: ["app", "deploy", "--version", "pull-request-number-$_PR_NUMBER-test", "--no-promote"]
    timeout: "1600s"
    
