steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Clean up old Versions
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        versions=$(gcloud app versions list --service=tobi-ui --sort-by='~version' --format='value(VERSION.ID)' --project=${PROJECT_ID} | tail -n +11)

        if [ -n "$versions" ]; then
          gcloud app versions delete "$versions"
            --service default
            --project ${PROJECT_ID}
            --quiet
        fi
