steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Clean up old Versions
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSIONS=$(gcloud app versions list --service 'tobi-ui' --sort-by '~version' --format 'value(version.id)' | sort -r | tail -n +10 | paste -sd " " -)
        echo $VERSIONS
        if [ ${#VERSIONS} -gt 0 ]
        then
          gcloud app versions delete --service 'tobi-ui' $VERSIONS -q
        else
          echo "No Versions to Clean Up"
        fi
