steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Clean up old Versions
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud app versions list --service 'tobi-ui' --sort-by '~version' --format 'value(version.id)' | sort -r | tail -n +10 | paste -sd " " -
        VERSIONS=$(gcloud app versions list --service 'tobi-ui' --sort-by '~version' --format 'value(version.id)' | sort -r | tail -n +10 | paste -sd " " -)
        echo $VERSIONS
