# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Formatting Code to eslint standards

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
#      - name: Formatting Code to eslint standards
#        uses: getsentry/action-eslint-fix@v2
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run linters
          uses: wearerequired/lint-action@v1
          with:
            github_token: ${{ secrets.github_token }}
            # Enable linters
            eslint: true
