name: Test and coverage

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run test-coverage
      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: "coverage/clover.xml"
          threshold_alert: 10
          threshold_warning: 50
      - name: Hello world action step
        id: hello
        uses: raulanatol/jest-coverage-comment-action@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jest-command: 'yarn run test-coverage'
